import React, { useState } from "react";
import "./pretask.css";
import { useNavigate } from "react-router-dom";
import Layout from "./Layout";
const PreTask = () => {
  const navigate = useNavigate();
  const [consent, setConsent] = useState(false);
  const [prolificId, setProlificId] = useState("");

  const handleConsentChange = (e) => {
    setConsent(e.target.checked);
  };

  const handleProlificIdChange = (e) => {
    setProlificId(e.target.value);
  };

  const handleProceed = () => {
    navigate("/task", { state: { prolificId } });
  };

  return (
    <Layout>
      <div className="pre-task-container">
        <h1>Human and LLM Collaboration in Text Summarization Tasks</h1>
        <div className="pre-task-contents">
          <h2>Informed Consent</h2>
          <p id="ic-container">
            We are a group of researchers at the Technical University of Delft
            (Delft University of Technology) in the Netherlands. In this
            research project, we aim to investigate the effects of integration
            approaches of large-language models (LLM) on the overall experience
            and performance of crowd-workers in text summarization tasks. This
            task is part of the research project described above.
            <br /> <br />
            You will encounter a series of texts that describe news articles
            from which you are tasked to: produce a summary between a word range
            and potentially propose edits to a revised version of your summary
            generated by a LLM in order to improve it (while adhering to the
            word range) review an existing summary of the text generated by a
            LLM and potentially propose edits to improve it in order to create
            your summary within a word range. to produce a summary while having
            the option to interact with a LLM that can help you in building a
            summary text within a word range. evaluate a text summary on its
            overall quality. For this task and each summary you create, you will
            be asked to adhere to a word limit expressed under the sample text
            which is to be summarized. We will collect this summary/evaluation
            along with the following demographic-related data: age, gender,
            experience, and occupation.
            <br /> <br />
            Your participation in this task is entirely voluntary and you can
            withdraw at any time. We do not collect any data aside from the
            information described above and your Prolific profile data that is
            automatically transmitted to us when you submit your answers. We
            will keep your information confidential. We ensure that your data is
            stored in a password-protected electronic format. Be aware that the
            data we gather with this task might be published in an anonymized
            form later. Such an anonymized data set would include the answers
            you provide in this task, but no personal information (e.g., your
            Prolific ID) so that the answers will not be traceable back to you.
            By completing the task and clicking 'submit' at the bottom of this
            page, you confirm that you have read, understood, and consent to all
            of the above information and the processing of your data. Once
            compensation has been provided, your data/responses cannot be
            withdrawn as we will not be able to identify your individual
            submission in the aggregated dataset, as your Prolific ID will be
            discarded from the dataset.
          </p>

          <label>
            <input
              type="checkbox"
              checked={consent}
              onChange={handleConsentChange}
            />
            I have read and understood the informed consent.
          </label>
        </div>
        <div className="pre-task-contents">
          <h2>Participant Information</h2>
          In order to receive compensation for your participation, please
          provide your Prolific ID below.
          <label>
            Prolific ID:
            <input
              type="text"
              value={prolificId}
              onChange={handleProlificIdChange}
            />
          </label>
          <button
            disabled={!consent || prolificId === ""}
            onClick={handleProceed}
          >
            Proceed to Task
          </button>
        </div>
      </div>
    </Layout>
  );
};

export default PreTask;
